// auto generated by go tool dist

package objabi

import "runtime"

const defaultGOROOT = `/Users/gabriel.aszalos/g/go`
const defaultGO386 = `sse2`
const defaultGOARM = `7`
const defaultGOOS = runtime.GOOS
const defaultGOARCH = runtime.GOARCH
const defaultGO_EXTLINK_ENABLED = ``
const version = `go1.9.2`
const stackGuardMultiplier = 1
const goexperiment = ``
